# SPDX-License-Identifier: GPL-2.0
ifdef CONFIG_KCSAN

cc-param = $(call cc-option, -mllvm -$(1), $(call cc-option, --param $(1)))

CFLAGS_KCSAN := -fsanitize=thread \
	$(call cc-param,tsan-distinguish-volatile=1)

endif # CONFIG_KCSAN
